### ISSUE TITLE
size of prompt tensor will not match if the length difference of two prompts is too large

### ISSUE THREAD

**Issue by jeffgyf** [Kahsolt/stable-diffusion-webui-prompt-travel#10]
```
Traceback (most recent call last):
  File "H:\workshop\diffussion\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "H:\workshop\diffussion\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "H:\workshop\diffussion\stable-diffusion-webui\modules\txt2img.py", line 49, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "H:\workshop\diffussion\stable-diffusion-webui\modules\scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "H:\workshop\diffussion\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\scripts\prompt_travel.py", line 471, in run
    images, info = self.run_linear()
  File "H:\workshop\diffussion\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\scripts\prompt_travel.py", line 566, in run_linear
    inter_pos_hidden = weighted_sum(from_pos_hidden, to_pos_hidden, alpha, kind='pos')
  File "H:\workshop\diffussion\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\scripts\prompt_travel.py", line 510, in weighted_sum
    condC = (1 - alpha) * condA + (alpha) * condB
RuntimeError: The size of tensor a (77) must match the size of tensor b (154) at non-singleton dimension 0
```

**Comment by jeffgyf** [comment]
A pair of prompts that can trigger this exception

Siamese cat with blue eyes, classical floral elements emanating from center of face, woodcutting template, decorative design, classical ornament, motif, bilateral symmetry, roses, leaves, flowers, buds, flowering buds, feathers, negative space, highly detailed etching, takes aim, in position, hero, rugged, rough, fearless, cinematic lighting, highly detailed, 4k, art by assassinmonkey
a dog

**Comment by jeffgyf** [comment]
Fixed by adding following lines befor prompt_travel.py line 510
```
                if condA.shape[0] < condB.shape[0]:
                    condA = torch.nn.functional.pad(condA, (0,0,0,condB.shape[0] - condA.shape[0]))
                elif condA.shape[0] > condB.shape[0]:
                    condA = torch.nn.functional.pad(condB, (0,0,0,condA.shape[0] - condB.shape[0]))
```

**Comment by Kahsolt** [comment]
Yes, this is a known bug. 
I did not consider it before because I did not make the test if zero padding will lead to generate some kinda nonsense.
If it is safe, could you please make a PR if possible? 😸

**Comment by Kahsolt** [comment]
OK, now it's there. With new features together ;)

**Comment by Matthieu-LAURENT39** [comment]
I'm still getting this issue on the latest commit (9c532f3487c69d533ae6637bae331f92ebb7b69f), with the exact same traceback.
Was there a regression?
