### ISSUE TITLE
Installed, but doesn't show in the "script"-pulldown

### ISSUE THREAD

**Issue by MajorGruberth** [Kahsolt/stable-diffusion-webui-prompt-travel#30]
I installed prompt travel, no errors, it shows in the "Extension" - menu, but NOT in the script-pulldown menu. Somebody care to explain? :>(

iMac M1, OS Ventura

Thanks!

**Comment by Kahsolt** [comment]
Does you console log complain anything? 🤔

**Comment by MajorGruberth** [comment]
yes:

---------------
Error loading script: prompt_travel.py
Traceback (most recent call last):
  File "/Users/xxxxx/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/Users/xxxxx/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/xxxxx/stable-diffusion-webui/extensions/stable-diffusion-webui-prompt-travel/scripts/prompt_travel.py", line 15, in <module>
    from moviepy.video.io.ImageSequenceClip import ImageSequenceClip
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/video/io/ImageSequenceClip.py", line 6, in <module>
    from ..VideoClip import VideoClip
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/video/VideoClip.py", line 18, in <module>
    from ..config import get_setting
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/config.py", line 36, in <module>
    FFMPEG_BINARY = get_exe()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/imageio/plugins/ffmpeg.py", line 173, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/imageio_ffmpeg/_utils.py", line 33, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.

---------------

So I need to install ffmpeg first? I'm wondering....

**Comment by Kahsolt** [comment]
It seems that `moviepy` requires manually installation of ffmpeg on unix-like system, see [https://github.com/Zulko/moviepy/issues/1158](https://github.com/Zulko/moviepy/issues/1158)
have a try of it ?

**Comment by MajorGruberth** [comment]
Well - moviepy manual says: ffmpeg is installed automatically. Actually I have the script called "ffmpeg.py" in the imageio - folder. Anyway: imageio-ffmpeg is installed and upgraded - so moviepy should know where to find it...
I still wondering, how many different ffmpeg-versions are around.... :)

BTW: "import os....0s.environ...." where do I change that? in the Terminal-settings under Profiles?

**Comment by Kahsolt** [comment]
Hi there, I just came back from a contest :)
As I reconsidered this problem, even if ffmpeg is not available on a machine, ptravel should still work with `export video` disabled (and apply postprocessing pipeline to compose a video file), so...
Why the hell does it not appear in the pull-down menu, might it be some gradio bugs I guess.

I seconds ago I just installed this extension [Cubemap-Tiling](https://github.com/LudoCrypt/Cubemap-Tiling), it also does not appear in UI. As I checked the code, it should be an AlwaysVisible extension.

Gradio or even a1111 webui is really heavy-weight and buggy, I'm digging deeper to find what's wrong.  :(
