### ISSUE TITLE
Do not work with SD.Next

### ISSUE THREAD

**Issue by sebaxakerhtc** [Kahsolt/stable-diffusion-webui-prompt-travel#36]
Hi. Thank you for this script
I try to use it in one of the best forks of Auto1111 - "SD.Next"
So, after last update I need to edit manually prompt-parser.py to add

```
class DictWithShape(dict):
    def __init__(self, x, shape):
        super().__init__()
        self.update(x)

    @property
    def shape(self):
        return self["crossattn"].shape
```
but then I have this problem on diffusers backend

```
n_stages: 3
n_frames: 23
steps: [10, 10]
seed: 1301783812
subseed: -1.0
subseed_strength: 0
[stage 1/3]
  pos prompt: a dog
  neg prompt:
Progress  2.15it/s ██████████████████████████████████████ 100% 20/20 00:09 00:00
[stage 2/3]
  pos prompt: a cat
  neg prompt:
Progress  2.11it/s ██████████████████████████████████████ 100% 20/20 00:09 00:00
Traceback (most recent call last):
  File "D:\auto-latest\automatic\extensions\stable-diffusion-webui-prompt-travel\scripts\prompt_travel.py", line 584, in run
    # Pack parameters
  File "D:\auto-latest\automatic\extensions\stable-diffusion-webui-prompt-travel\scripts\prompt_travel.py", line 644, in run_linear
    process_p()
  File "D:\auto-latest\automatic\extensions\stable-diffusion-webui-prompt-travel\scripts\prompt_travel.py", line 136, in wrapper
  File "D:\auto-latest\automatic\extensions\stable-diffusion-webui-prompt-travel\scripts\prompt_travel.py", line 129, in cond_align
    CHOICES_REPLACE_DIM     = [x.value for x in ModeReplaceDim]
AttributeError: 'NoneType' object has no attribute 'shape'
```

Can you help with it?

**Comment by Kahsolt** [comment]
hello~ where can I find this fork "SD.Next"? it seems alike a new front end...?
I'd like to check it and decide whether to support it in the `master` or a new branch of this repo :)

**Comment by sebaxakerhtc** [comment]
> hello~ where can I find this fork "SD.Next"? it seems alike a new front end...? I'd like to check it and decide whether to support it in the `master` or a new branch of this repo :)

Hey, it's just a nomber 1 fork (vladmandic - automatic) I forget it was renamed :) sorry
<img width="652" alt="Снимок экрана 2023-08-07 в 14 56 17" src="https://github.com/Kahsolt/stable-diffusion-webui-prompt-travel/assets/32651506/9e3dccb4-119b-4c72-b576-a90bfcafd578">
https://github.com/vladmandic/automatic

**Comment by Kahsolt** [comment]
Thx~ I'll check it soon :)

**Comment by sebaxakerhtc** [comment]
Thank you!
If you'll need any info - let me know!

**Comment by Kahsolt** [comment]
Here's a question~
You are NOT using a SDXL model ckpt right?

This `DictWithShape` is for added in A1111's stream to support SDXL, and the vlad's may come up with it later (?)
You can try revert ptravel version to `v3.0` (commit 98a65237aa9d6f8c52d3861edb83b74b6d133ebb)

```
cd extensions/stable-diffusion-webui-prompt-travel
git checkout 98a6523
```

and check if it works for you temporarily

**Comment by sebaxakerhtc** [comment]
> You are NOT using a SDXL model ckpt right?

Wrong - I'm using SDXL.
On non-sdxl (original) backend it works fine after adding DictWithShape to prompt_parser



> the vlad's may come up with it later (?)

Not so. Vlad's fork uses diffusers backend for SDXL - it works differently



> and check if it works for you temporarily

Yes, tried it already, but have the same `AttributeError: 'NoneType' object has no attribute 'shape'` but differently showed.
I'll provide it soon

**Comment by sebaxakerhtc** [comment]
As you can see - it generates first image, then a second and stops with this

**Comment by sebaxakerhtc** [comment]
I'm looking at the script and found this
`from modules.processing`
But there's a new file named `processing_diffusers.py` which I think used instead of `processing.py` on diffusers backend with SDXL

**Comment by Kahsolt** [comment]
thx for the info, I've just installed the vlad's and started to test.
you may be right, I guess that hooks for the `original` backend might not work for `diffuser` backend
I'm inspecting deeper

**Comment by sebaxakerhtc** [comment]
@Kahsolt  thank you for your time and a great work!

**Comment by Kahsolt** [comment]
Well, sadly to confirm that this `diffusers` backend is very simplified, and it does not utilize the original callback system (see stuff in `modules.script_callbacks`), so we can NOT peek the condition tensor for interpolation (got 'NoneType' error)

And yet good news... you're always welcome back to A1111 lol :)
