### ISSUE TITLE
Error loading script: prompt_travel.py in A1111's webui

### ISSUE THREAD

**Issue by XrealityF23** [Kahsolt/stable-diffusion-webui-prompt-travel#37]
Hi
I´ve seen this issue turning up, but couldn´t figure out how to fix this. please advice.
grateful for help,
best regards
/Mikael

Error loading script: prompt_travel.py
Traceback (most recent call last):
File "C:\Users\Mikael\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "C:\Users\Mikael\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
module_spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in _call_with_frames_removed
File "C:\Users\Mikael\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\scripts\prompt_travel.py",
line 34, in
from modules.prompt_parser import DictWithShape
ImportError: cannot import name 'DictWithShape' from 'modules.prompt_parser'
(C:\Users\Mikael\stable-diffusion-webui\modules\prompt_parser.py)

**Comment by Kahsolt** [comment]
I'll soon sync with the sd-webui v1.6.0 updates :) wait for a while
