### ISSUE TITLE
ModuleNotFoundError: No module named '_tkinter'

### ISSUE THREAD

**Issue by evanerichards** [Kahsolt/stable-diffusion-webui-prompt-travel#40]
I'm in auto1111
version: [1.6.0]
python: 3.10.11
torch: 2.0.1+cu118
xformers: 0.0.22

[ControlNet-Travel] extension Mikubill/sd-webui-controlnet found, ControlNet-Travel loaded :)
*** Error loading script: controlnet_travel.py
    Traceback (most recent call last):
      File "E:\StabilityMatrix\Data\Packages\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\StabilityMatrix\Data\Packages\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\StabilityMatrix\Data\Packages\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\scripts\controlnet_travel.py", line 45, in <module>
        from manager import run_cmd
      File "E:\StabilityMatrix\Data\Packages\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\manager.py", line 12, in <module>
        from PIL.ImageTk import PhotoImage
      File "E:\StabilityMatrix\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageTk.py", line 28, in <module>
        import tkinter
      File "E:\StabilityMatrix\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\tkinter\__init__.py", line 37, in <module>
        import _tkinter # If this fails your Python may not be configured for Tk
    ModuleNotFoundError: No module named '_tkinter'

But when I run `python -m tkinter` it says that it is installed. Any thoughts?

**Comment by Kahsolt** [comment]
Now `controlnet_travel.py` does not rely on `manager.py`, hence this issue should be solved.
However doesn't know if the ControlnetTravel feature still works? 🤔
