### ISSUE TITLE
Exception: Moviepy: ImageSequenceClip requires all images to be the same size && IndexError: tuple index out of range

### ISSUE THREAD

**Issue by danzeeeman** [Kahsolt/stable-diffusion-webui-prompt-travel#43]
I keep getting this when I try to run prompt-travel with AnmiDiff and ControlNet

Traceback (most recent call last):
  File "C:\tools\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\scripts\prompt_travel.py", line 621, in run
    runner()
  File "C:\tools\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\scripts\prompt_travel.py", line 668, in run_linear
    imgs = process_p(append=False)      # stash it to make order right
  File "C:\tools\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\scripts\prompt_travel.py", line 438, in process_p_binding_
    proc = process_images(self.p)
  File "C:\tools\stable-diffusion-webui\modules\processing.py", line 734, in process_images
    res = process_images_inner(p)
  File "C:\tools\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 94, in hacked_processing_process_images_hijack
    unit.batch_images = shared.listfiles(unit.batch_images)
  File "C:\tools\stable-diffusion-webui\modules\util.py", line 13, in listfiles
    filenames = [os.path.join(dirname, x) for x in sorted(os.listdir(dirname), key=natural_sort_key) if not x.startswith(".")]
TypeError: listdir: path should be string, bytes, os.PathLike or None, not list

Traceback (most recent call last):
  File "C:\tools\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\scripts\prompt_travel.py", line 355, in save_video
    clip = ImageSequenceClip(seq, fps=video_fps)
  File "C:\tools\stable-diffusion-webui\venv\lib\site-packages\moviepy\video\io\ImageSequenceClip.py", line 91, in __init__
    raise Exception("Moviepy: ImageSequenceClip requires all images to be the same size")
Exception: Moviepy: ImageSequenceClip requires all images to be the same size

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\tools\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\scripts\prompt_travel.py", line 357, in save_video
    clip = concatenate_videoclips([ImageClip(img, duration=1/video_fps) for img in seq], method='compose')
  File "C:\tools\stable-diffusion-webui\venv\lib\site-packages\moviepy\video\compositing\concatenate.py", line 75, in concatenate_videoclips
    w = max(r[0] for r in sizes)
  File "C:\tools\stable-diffusion-webui\venv\lib\site-packages\moviepy\video\compositing\concatenate.py", line 75, in <genexpr>
    w = max(r[0] for r in sizes)
IndexError: tuple index out of range

**Comment by Kahsolt** [comment]
AnimeDiff might not work with this extension. 🤔
Since AnmiDiff itself alrealy re-implemented the prompt-travel mechanism inside that repo, you'd better follow their instruction.

AnimeDiff 's prompt-travel feature does not rely on this (more ancient implementation) prompt-travel :)
