### ISSUE TITLE
Prompt Travel won't install properly

### ISSUE THREAD

**Issue by HalLupus** [Kahsolt/stable-diffusion-webui-prompt-travel#46]
Hello! 
I've seen either this issue, or similar issues pop up a few times, but I can't seem to get prompt travel to install properly.
I greatly appreciate any form of help. 
Best regards,
HalLupus

I'm on macOS version 13.5.3
I've also recently (yesterday) did a git pull after the extension wasn't working on my previous version, and now I'm on sd version [v1.6.0-2-g4afaaf8a]

What I get when I start up sd:

*** Error loading script: controlnet_travel.py
    Traceback (most recent call last):
      File "/Users/(username)/Documents/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/(username)/Documents/stable-diffusion/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/(username)/Documents/stable-diffusion/stable-diffusion-webui/extensions/stable-diffusion-webui-prompt-travel/scripts/controlnet_travel.py", line 45, in <module>
        from scripts.prompt_travel import *
      File "/Users/(username)/Documents/stable-diffusion/stable-diffusion-webui/extensions/stable-diffusion-webui-prompt-travel/scripts/prompt_travel.py", line 24, in <module>

*** Error loading script: prompt_travel.py
    Traceback (most recent call last):
      File "/Users/(username)/Documents/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/(username)/Documents/stable-diffusion/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/(username)/Documents/stable-diffusion/stable-diffusion-webui/extensions/stable-diffusion-webui-prompt-travel/scripts/prompt_travel.py", line 24, in <module>

**Comment by Kahsolt** [comment]
I got it, you might have an envvar FFMPEG_BINARY pointing to a broken path.
I'll force it to moviepy's default in a fix
