### ISSUE TITLE
New controlnet version is causing an error

### ISSUE THREAD

**Issue by shtorm2005** [Kahsolt/stable-diffusion-webui-prompt-travel#48]
ControlNet travel script error

2023-12-08 23:05:58,054 - ControlNet - INFO - unit_separate = True, style_align = False
2023-12-08 23:05:58,054 - ControlNet - INFO - Loading model from cache: diff_control_sd15_temporalnet_fp16 [adc6bd97]
2023-12-08 23:05:58,055 - ControlNet - INFO - Loading preprocessor: none
2023-12-08 23:05:58,056 - ControlNet - INFO - preprocessor resolution = 576
*** Error running process: C:\Users\Admin\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Users\Admin\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "C:\Users\Admin\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1053, in process
        self.controlnet_hack(p)
      File "C:\Users\Admin\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1042, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\Users\Admin\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1014, in controlnet_main_entry
        self.latest_network.hook(model=unet, sd_ldm=sd_ldm, control_params=forward_params, process=p,
    TypeError: hook_hijack() got an unexpected keyword argument 'batch_option_uint_separate'

**Comment by shtorm2005** [comment]
I find this a cool feature to use images instead of words for traveling. Of course, if it takes too much time, it's not worth updating. Btw, thanks for a great extension.
