### ISSUE TITLE
Runtime error "AttributeError: 'TypeVar' object has no attribute 'ToTensor'" when SSIM enabled

### ISSUE THREAD

**Issue by sglasman** [Kahsolt/stable-diffusion-webui-prompt-travel#49]
I'm in a Vast.ai instance running the runpod webui 10.1.1 image. This error shows after the first pass of generations when SSIM is enabled. Full stack trace:

Traceback (most recent call last):
File "/workspace/stable-diffusion-webui/extensions/stable-diffusion-webui-prompt-travel/scripts/prompt_travel.py", line 578, in run
runner()
File "/workspace/stable-diffusion-webui/extensions/stable-diffusion-webui-prompt-travel/scripts/prompt_travel.py", line 663, in run_linear
) = self.ssim_loop(
File "/workspace/stable-diffusion-webui/extensions/stable-diffusion-webui-prompt-travel/scripts/prompt_travel.py", line 842, in ssim_loop
transform = T.ToTensor()
AttributeError: 'TypeVar' object has no attribute 'ToTensor'

I've already tried removing the --skip-install command line argument, which has helped with other extension issues.

**Comment by mcDandy** [comment]
I have the same problem. It worked on commit 4afaaf8a020c1df457bcf7250cb1c7f609699fa7 of A1111 but as of cf2772fab0af5573da775e7437e6acdca424f26e it fails with this error.

**Comment by Kahsolt** [comment]
Hello friends, thanks for the bug report.
Have a try of the latest commit for the bug fix

**Comment by mcDandy** [comment]
Honestly forgot abt this. I am sure it was fixed...
