### ISSUE TITLE
ImportError: cannot import name 'FrozenCLIPEmbedderWithCustomWords' from 'modules.sd_hijack'

### ISSUE THREAD

**Issue by Harvester62** [Kahsolt/stable-diffusion-webui-prompt-travel#5]
After the most recent update of SD Web UI (https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/b5050ad2071644f7b4c99660dc66a8a95136102f) I get this error message in the console:

Error loading script: prompt_travel.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\scripts\prompt_travel.py", line 264, in <module>
    from modules.sd_hijack import FrozenCLIPEmbedderWithCustomWords
ImportError: cannot import name 'FrozenCLIPEmbedderWithCustomWords' from 'modules.sd_hijack' (C:\stable-diffusion-webui\modules\sd_hijack.py)

**Comment by Kahsolt** [comment]
Oh I see.. I've pushed a fix tagged v1.2-fix2 hours ago, it should work now. Thanx for quick informing~
