### ISSUE TITLE
Successive Frame genesis and ControlNet cannot work together

### ISSUE THREAD

**Issue by chchan585** [Kahsolt/stable-diffusion-webui-prompt-travel#50]
I am trying to generate images with Successive Frame genesis and ControlNet, but seems it always get the tensor size error. Below is my test set:

**Prompt:** 
Cute Cat
Cute Dog

**Frame genesis:** successive

**ControlNet Prepocessor:** depth_midas
**ControlNet Model:** control_v11fp_sd15_depth

And i am using the suggested version:
[AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui): version v1.5.1, tag [v1.5.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.5.1)
[Mikubill/sd-webui-controlnet](https://github.com/Mikubill/sd-webui-controlnet): version v1.1.229, commit [eceeec7a7e](https://github.com/Mikubill/sd-webui-controlnet/commit/eceeec7a7e856867de56e26cae9f3e1076480344)

Everytime I try this got this error:

```
Traceback (most recent call last):
File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\scripts\prompt_travel.py", line 621, in run
runner()
File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\scripts\prompt_travel.py", line 681, in run_linear
inter_pos_hidden.value = lerp_fn(from_pos_hidden.value, to_pos_hidden.value, alpha)
File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\scripts\prompt_travel.py", line 169, in wrapper
return fn(condA, condB, *args, **kwargs)
File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\scripts\prompt_travel.py", line 176, in weighted_sum
return (1 - alpha) * A + (alpha) * B
RuntimeError: The size of tensor a (78) must match the size of tensor b (77) at non-singleton dimension 1
```

Is Successive  + ControlNet not supported or something happened?

**Comment by nVen0m1** [comment]
I am having the same problem. I built a new rig and installed a fresh a1111/AnimateDiff/Prompt Travel/Controlnet and I am getting the same error when attempting to prompt travel: My old machine is setup exactly the same way and everything is still working fine. Please help.
