### ISSUE TITLE
IndexError: List index out of range

### ISSUE THREAD

**Issue by clarkxl** [Kahsolt/stable-diffusion-webui-prompt-travel#6]
`Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/notebooks/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/notebooks/stable-diffusion-webui/modules/txt2img.py", line 46, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "/notebooks/stable-diffusion-webui/modules/scripts.py", line 317, in run
    processed = script.run(p, *script_args)
  File "/notebooks/stable-diffusion-webui/extensions/stable-diffusion-webui-prompt-travel/scripts/prompt_travel.py", line 517, in run
    while len(neg_prompts) < n_stages: neg_prompts.append(neg_prompts[-1])
IndexError: list index out of range`

Am using a 48GB vram A6000 on Gradient, and i get this error whenever i try to run a generation, might be doing something wrong though

**Comment by clarkxl** [comment]
Changing to a different sampler that wasnt Euler fixed it

**Comment by Kahsolt** [comment]
Thx for attention~
I checked and found this is indeed a small bug - it will always fail when negative_prompt is empty.
Now its fixed :)
