### ISSUE TITLE
AttributeError: 'FrozenCLIPEmbedderWithCustomWords' object has no attribute 'process_text'

### ISSUE THREAD

**Issue by Noctree** [Kahsolt/stable-diffusion-webui-prompt-travel#9]
I'm running SD WebUI latest branch (0b8911d) in Google Colab using a notebook from [TheLastBen](https://github.com/TheLastBen/fast-stable-diffusion)

Getting this error:

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 49, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-prompt-travel/scripts/prompt_travel.py", line 683, in run
    if   mode == 'linear' : images, info = self.run_linear()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-prompt-travel/scripts/prompt_travel.py", line 749, in run_linear
    from_pos_hidden, from_neg_hidden, prompts, seeds, subseeds = process_images_prompt_to_cond(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-prompt-travel/scripts/prompt_travel.py", line 161, in process_images_prompt_to_cond
    uc, uc_tokens, uc_weights = get_learned_conditioning(shared.sd_model, negative_prompts, p.steps)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-prompt-travel/scripts/prompt_travel.py", line 258, in get_learned_conditioning
    conds, tokens, weights = LatentDiffusion_get_learned_conditioning(model, texts)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-prompt-travel/scripts/prompt_travel.py", line 409, in LatentDiffusion_get_learned_conditioning
    c, tokens, weights = FrozenCLIPEmbedderWithCustomWords_forward(self.cond_stage_model, c)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-prompt-travel/scripts/prompt_travel.py", line 394, in FrozenCLIPEmbedderWithCustomWords_forward
    batch_multipliers, remade_batch_tokens, used_custom_terms, hijack_comments, hijack_fixes, token_count = text_to_token(self, text)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-prompt-travel/scripts/prompt_travel.py", line 331, in text_to_token
    batch_multipliers, remade_batch_tokens, used_custom_terms, hijack_comments, hijack_fixes, token_count = self.process_text(text)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'FrozenCLIPEmbedderWithCustomWords' object has no attribute 'process_text'
```

**Comment by Kahsolt** [comment]
Hello~ Thanks for the information.
The newest commit with tag v1.4 should rework now, change log in readme is also updated to explain what happened & why in detail.

**Comment by Noctree** [comment]
Unfortunate that the changes were breaking 😟
However the issue is fixed now. Thank you,
